#
# <libname>.conf
#
# Configuration file for <LIB_NAME> Library.
#
# Set default configuration variables in this file for <LIB_NAME> Library.
# Variables set in here might get overwritten by <libname>ctl at runtime
# by options or other parameters. See Library README.md for more infos about this.
#
# Note: This is a default template conf file.
#       Replace <LIB_NAME> to the library you want to create
#       copy and rename this file to _<lib>dir/default/<lib>.conf,
#       where <lib> is the name of your new library.
#
_LIB_TO_LOAD=lib2
_OTHER_PARAM=foo
