#!/usr/bin/env bash
#
# <libname>ctl
#
# Shell control utility for <LIB_NAME> Library.
#
# This is the control utility file for <LIB_NAME> Library.
#
# Control Utilities mimic the behaviour of systemctl controlfiles,
# just that no system service is started/stopped, but rather a library function
# gets loaded and variables are set by otions supplied, or values set in default.conf.
#
# At least this file should contain the methods (mandatories are marked with an asteriks):
#
# - options     (process options supplied at commanline)
# - init*       (initialize library by loading its main function into session memory)
# - configure   (configure runtime behaviour of library or persit settings in <libname>.conf)
# - start*      (start a function or a script  execution,
#                or just return current status if there is nothing to start)
# - stop*       (start a function or a script  execution, or unload main function from memory)
# - status*     (return current status of library: loaded into memory, or not)
# - help*       (more detailed help about this file)
# - usage       (small description if parameters or arguments are missing or wrong)
#
# Note: This is a default template file.
#       Replace <LIB_NAME> to the library you want to create
#       copy and rename this file to _<lib>dir/<lib>ctl, where <lib> is the name of your new library.
#
# See help function for more info about the use and appliance of this file.
#
# History:
#    2024-09-23 - sobermeyer: created.
#
#

## Variables
_FILE=${0}
_THIS_PID=${$}
_THIS_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
_THIS_FILE=$(basename ${_FILE})
_THIS_DEBUG=false

_LIB_BASE=$(dirname $(find ${HOME} -type f -name "libctl"))
_LIB_NAME=$(basename ${_THIS_DIR})
_LIB_DEFAULT_CONF=${_THIS_DIR}/default/${_LIB_NAME}.conf

_CALLER_PID=$((${_THIS_PID} - 1))
[[ $(ps -o stat= -p ${$}) == $(ps -o stat= -p ${PPID}) ]] && {
    ## called from other script
    _CALLER_PID=${PPID}
    _CALLED_BY=$(ps -fp ${PPID} | grep -v grep | grep ${PPID} | awk '{print $NF}')
} || {
    ## called standalone
    _CALLER_PID=${_THIS_PID}
    _CALLED_BY=${_FILE}
}

_LINE="********************************************************************************"
_SHIFT_CNT=0;

## Functions

# usage
function _usage() {
    echo "Usage: ${_THIS_FILE}: [option] [parameter (value)]"
    echo "       run ${_THIS_FILE} --help for more details."
}

[ ${#} -eq 0 ] && { _usage; exit 0; }

# blank line
function _blank() {
    echo;
}

# log entry
function _log_entry() {
    echo "$(date) - ${1}"
}

# log line
function _log_line() {
    [ -z ${1} ] && _len=${#_LINE} || _len=${1}
    echo "$(date)   ${_LINE:0:${_len}}"
}


# debug
function _debug() {
    _THIS_DEBUG=true;
    _log_line 76
    _log_entry "Local Variables used in ${_THIS_FILE}";
    _log_entry "LibBase:       ${_LIB_BASE}"
    _log_entry "LibDir:        ${_THIS_DIR}"
    _log_entry "LibName:       ${_LIB_NAME}"
    _log_entry "File:          ${_THIS_FILE}"
    _log_entry "FileSource:    ${BASH_SOURCE[1]}"
    _log_entry "My PID:        ${_THIS_PID}"
    _log_entry "Called by:     ${_CALLED_BY}"
    _log_entry "Caller PID:    ${_CALLER_PID}"
    _log_line 76
    _SHIFT_CNT=1;
}

# help
function _help () {
#*******************************************************************************

## your elaborated help text goes here
## (examples for using man page format, see $_LIB_DIR/default/examples)
cat | more <<EOF
NAME
    ${_THIS_FILE} - control behaviour of a shell library.

SYNOPSIS
    ${_THIS_FILE} [options] parameters

DESCRIPTION
    ${_THIS_FILE} is used to control shell libraries and their runtime behaviour.

    The parameters ${_THIS_FILE} is called with can be divided into two parts:
    Options which modify the way ${_THIS_FILE} works.
    The second part are arguments to make ${_THIS_FILE} to control the behaviour
    of the libraries file it will invoke.

OPTIONS
    -d | --debug    run ${_THIS_FILE} in debug mode (output of runtime variables)

    -h | --help     show this help text.

COMMANDS
    init(ialize)    initialize the function to be loaded. In this step the
                    default configuration file of the Library is loaded
                    and then any option that is passed in to this script is
                    processed and applied (which effectively can overwrite
                    variables or parameters set in the default configuration file).
                    Then the function to be loaded is evaluated based on the
                    values previously set. It does so by choosing the file that
                    contains the function to be loaded.

                    For example: there are three different logging libraries,
                    each with a function called _log. Based on the runtime
                    variable _LOGGER=<name_of_logger_library>, the appropriate
                    file is sourced and the function _log is loaded into session memory.
                    This is done by creating a temporary file with the name
                    \$TMP_DIR/<PID_of_caller>_<name_of_function>.sh to support
                    parallel use of libraries in different scripts at the same time.

                    The temporary file is bound to the calling script and
                    removed at the end of its run by using "${_THIS_FILE} stop"
                    (see stop for more details on this).

    conf(igure)     configures the behaviour of this script, or the library to load.
                    It does so by creating an additional configuration file
    [-b|--backup]   that is read after all options have been processed in the
                    init phase of this script. The configure argument can be supplied
                    one option -b | --backup to create a backup of the default
                    configuration file when edited by configure.

                    For example: another TMP directory than the default should be used,
                    then it can be configured by this argument and value.

    start [script]  Starts a script or function call, depending of the use case
                    of the library called. If there is nothing to start
                    because if there is just a function loaded it is available then.
                    But there are cases when libraries start something like another
                    shell script or a service. In these cases its useful to pass
                    a start command to the library.

    stop [--keep]   Stops the library function or script.
                    If its a script the process will be terminated.
                    If its a function loaded into session memory, it will be unset.
                    Any temporary files used at runtime will be deleted,
                    if the -k | --keep option of the stop argument is not supplied.

    status          Displays the current status of the library loaded.
                    Either the PID of the script or the availability of a function in
                    memory are displayed together with some useful information
                    about the run context of the library, like configuration file used, etc.

AUTHOR
    Stefan Obermeyer ⟨sobermeyer@kzvnr.de⟩

AVAILABILITY
    The ${_THIS_FILE} command is part of the lib package and is available from
    Oracle Scripts GIT repository
    ⟨https://gitlab.kzvnr.de/kzvdba/oracle/-/tree/stage/scripts/lib?ref_type=heads⟩.

LAST UPDATE
    September 2024

EOF
}


# Options for this file (other options may be provided for parameters and parsed in function)
function _parse_options () {
    [ ${#} -gt 0 ] && {
        ## processing script options for debug or show help using getopt
        OPTS=$(getopt --quiet --options dh --longoptions debug,help: -- "$@")
        ## These options are mutually exclusive, so break on each hit in case statement
        eval set -- "${OPTS}"
        while true; do
            case "${1}" in
            -h | --help )
                _blank;
                _log_entry "${_THIS_FILE} Help";
                _help;
                shift; break;
            ;;
            -d | --debug)
                _debug;
                shift; break;
            ;;
            -- ) shift; break;
            ;;
            * ) break;
            ;;
            esac
        done
    } || {
        _log_entry "${_LIB_NAME}: no Options set"
        return 0;
    }
}


# init
function _init() {
    echo "Init ${1}"
}


# configure
function _configure () {
    [ ${_THIS_DEBUG} ] && _log_entry "Function: \"${FUNCNAME[0]}\" - Parameter: ${PARAMS}"
    _BCK="";
    while [ ${#} -gt 0 ]; do
        case "${1}" in
                -b | --backup )
                    _log_entry "${FUNCNAME[0]} -> setting backup flag";
                    _BCK=".bak"
                    shift; break;
                ;;
        esac
    done
    _CONFIG_PARAM=$(echo ${1} | cut -f1 -d=)
    _CONFIG_VALUE=$(echo ${1} | cut -f2 -d=)
    _CURRENT_VALUE=$(cat ${_LIB_DEFAULT_CONF} | grep ${_CONFIG_PARAM} | cut -f2 -d=)
    [ ${_THIS_DEBUG} ] && _log_entry "_CURRENT_VALUE=${_CURRENT_VALUE} - _CONFIG_VALUE=${_CONFIG_VALUE} - BackupFlag=${_BCK}"

    sed -i${_BCK} "s/${_CURRENT_VALUE}/${_CONFIG_VALUE}/g" ${_LIB_DEFAULT_CONF}
}


# start
function _start () {
    echo "Start something"
}


# stop
function _stop () {
    echo "Stop something"
}


# status
function _status () {
    echo "Current Status"
}


## Processing

# parse internal options
_parse_options "${@}"

# shifting params, if needed
[ ${_THIS_DEBUG} ] && _log_entry "ShiftCount=${_SHIFT_CNT}"
[ ${_SHIFT_CNT} -gt 0 ] && shift ${_SHIFT_CNT}
PARAMS="${@}"

# processing COMMANDS
while [ ${#} -gt 0 ]; do
    case "${1}" in
    conf | configure )
        shift;
        _configure ${@};
        break;
    ;;
    init | initialize)
        echo "init"
        shift;
        _init;
        break;
    ;;
    start)
        echo "start"
        _start;
        shift; break;
    ;;
    stop)
        echo "stop"
        _stop;
        shift; break;
    ;;
    status)
        echo "status"
        _status;
        shift; break;
    ;;
    * ) break;
    ;;
    esac
done

exit ${?}
